FROM adhdtech/drp-nodejs:alpine

RUN apk add --update libaio libnsl libc6-compat && \
    ln -s /usr/lib/libnsl.so.3 /usr/lib/libnsl.so.1 && \
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 && \
    ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2

# Define app directory
ENV APPDIR=/app
ENV NODE_ENV=production

# Create app directory
WORKDIR /app

RUN npm install --production dotenv axios node-rest-client mssql oracledb stomp-client cucm-sql-async ldapjs csv-string neo4j-driver pg simple-git node-ssh ssh2shell mongodb @influxdata/influxdb-client
# If you are building your code for production
# RUN npm ci --only=production

LABEL cisco.info.name="drp-nodejs-full" \
      cisco.info.description="DRP Node.js Server" \
      cisco.info.version="alpine" \
      cisco.info.author-link="https://adhdtech.com" \
      cisco.info.author-name="Pete Brown" \
      cisco.type=docker \
      cisco.cpuarch=x86_64 \
      cisco.resources.profile=custom \
      cisco.resources.cpu=400 \
      cisco.resources.memory=128 \
      cisco.resources.disk=128 \
      cisco.resources.network.0.interface-name=eth0 \
      cisco.resources.network.0.ports.tcp=[8080]

EXPOSE 8080
CMD [ "node", "server.js" ]
