FROM alpine:latest

RUN apk add --update npm

# Define app directory
ENV APPDIR=/app
ENV NODE_ENV=production

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY drp-mesh drp-mesh
COPY drp-swaggerui drp-swaggerui
COPY drp-service-sidecar drp-service-sidecar
COPY drp-service-rsage drp-service-rsage
COPY drp-service-test drp-service-test
RUN mkdir webroot
COPY webroot/assets webroot/assets
COPY webroot/favicon.ico webroot
RUN mkdir webroot/vdmapplets
COPY webroot/vdmapplets/vdm-app-AppletEditor.js webroot/vdmapplets
COPY webroot/vdmapplets/vdm-app-CommandTesting.js webroot/vdmapplets
COPY webroot/vdmapplets/vdm-app-DRPShell.js webroot/vdmapplets
COPY webroot/vdmapplets/vdm-app-DRPTopology.js webroot/vdmapplets
COPY webroot/vdmapplets/vdm-app-RickRoll.js webroot/vdmapplets
COPY webroot/vdmapplets/vdm-app-TopicWatch.js webroot/vdmapplets
RUN mkdir webroot/xrapplets
COPY package-base.json package.json
COPY server.js .
COPY drpRegistry.js .
COPY drpBroker.js .
COPY drpConsumer.js .
COPY drpSidecar.js .
COPY drpLinc.js .
COPY lincTest.cfg .
COPY drpProvider-Test.js .
COPY drpProvider-Test-NoListener.js .
COPY drpProvider-Test-Authenticator.js .

RUN npm install --production
# If you are building your code for production
# RUN npm ci --only=production

LABEL cisco.info.name="drp-nodejs" \
      cisco.info.description="DRP Node.js Server" \
      cisco.info.version="latest" \
      cisco.info.author-link="https://adhdtech.com" \
      cisco.info.author-name="Pete Brown" \
      cisco.type=docker \
      cisco.cpuarch=x86_64 \
      cisco.resources.profile=custom \
      cisco.resources.cpu=400 \
      cisco.resources.memory=128 \
      cisco.resources.disk=128 \
      cisco.resources.network.0.interface-name=eth0 \
      cisco.resources.network.0.ports.tcp=[8080]

EXPOSE 8080
CMD [ "node", "server.js" ]
