descriptor-schema-version: "2.7"
info:
  name: drp-nodejs-small
  description: DRP Node.js Server
  version: latest
  author-link: https://adhdtech.com
  author-name: Pete Brown
app:
  cpuarch: x86_64
  env:
    APPDIR: /app
    NODE_ENV: production
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    cpu: 400
    disk: 128
    memory: 128
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "8080"
    profile: custom
  startup:
    rootfs: rootfs.tar
    target:
    - node
    - server.js
    workdir: /app
  type: docker
